### ISSUE TITLE
 64-bit test appliance  root_fs.img.x86_64 missing?

### ISSUE THREAD

**Issue by Lakshmipathi** [tytso/xfstests-bld#20]
Hi, 

Looks like 64 bit appliance mentioned in [kvm-xfstests](https://github.com/tytso/xfstests-bld/blob/master/Documentation/kvm-xfstests.md) is missing. root_fs.img download  [link](https://www.kernel.org/pub/linux/kernel/people/tytso/kvm-xfstests/root_fs.img.x86_64) gets redirect to this [one](https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/kvm-xfstests/root_fs.img.x86_64) and displays 404 error message `Sorry, we cannot find your kernels` . Is it removed or some other issue?

**Comment by tytso** [comment]
I've fixed the documentation.   I changed the filename to be root_fs.img.amd64, since amd64 is the Debian name for the 64-bit x86 architecture, and it made the release build and upload automation simpler.
