### ISSUE TITLE
build-all failed because "config.guess: unable to guess system type"

### ISSUE THREAD

**Issue by Cypresslin** [tytso/xfstests-bld#21]
With Ubuntu 18.04 Bionic (4.15.0-60-generic) running on a PowerPC
The ./build-all from make command failed with:

>    ./build-all
  ----------------- 2019-09-04 08:11:33: Starting build of extended attribute library
  checking build system type... Makefile:31: recipe for target 'all' failed
  stderr:
  configure: WARNING: unrecognized options: --disable-nls
  ./config.guess: unable to guess system type
  
  > This script, last modified 2012-06-10, has failed to recognize
  the operating system you are using. It is advised that you
  download the most up to date version of the config scripts from
  
  >  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
  and
    http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
  
 > If the version you run (./config.guess) is already up to date, please
  send the following data and any information you think might be
  pertinent to <config-patches@gnu.org> in order to provide the needed
  information to handle your system.
  
 > config.guess timestamp = 2012-06-10
  
 > uname -m = ppc64le
  uname -r = 4.15.0-60-generic
  uname -s = Linux
  uname -v = #67-Ubuntu SMP Thu Aug 22 16:54:48 UTC 2019
  
>  /usr/bin/uname -p = 
  /bin/uname -X     = 
  
>  hostinfo               = 
  /bin/universe          = 
  /usr/bin/arch -k       = 
  /bin/arch              = 
  /usr/bin/oslevel       = 
  /usr/convex/getsysinfo = 
  
>  UNAME_MACHINE = ppc64le
  UNAME_RELEASE = 4.15.0-60-generic
  UNAME_SYSTEM  = Linux
  UNAME_VERSION = #67-Ubuntu SMP Thu Aug 22 16:54:48 UTC 2019
  configure: error: cannot guess build type; you must specify one
  make: *** [all] Error 1

For the config.guess files, there are:

>./acl/build-aux/config.guess
./attr/config.guess
./e2fsprogs-libs/config/config.guess
./popt/config.guess

Replace the config.guess / config.sub in attr/ with the suggested new version can fix this issue.

**Comment by tytso** [comment]
Fixed as of commit 3a6b79e9c383534f72d55057857dc8282fc98e95
