### ISSUE TITLE
ext4/304 passed with Ubuntu Disco

### ISSUE THREAD

**Issue by Cypresslin** [tytso/xfstests-bld#25]
It looks like ext4/304 is not failing anymore, passed with Ubuntu Disco (5.0.0-29-generic)

    04:10:45 DEBUG| [stdout] ext4/303	 75s
    04:11:20 DEBUG| [stdout] ext4/304	 35s
    04:11:23 DEBUG| [stdout] ext4/305	 3s

Perhaps it can be removed from the kvm-xfstests/test-appliance/files/root/fs/ext4/exclude exclusion file?

**Comment by tytso** [comment]
Thanks for pointing this out!  I've removed this from the exclude list.
