### ISSUE TITLE
FR: support --no-email option for ltm commands

### ISSUE THREAD

**Issue by lrumancik** [tytso/xfstests-bld#46]
When running LTM commands for selftests, we likely don't want to receive emails. Right now, --no-email is only supported for pure gce-xfstests commands (gce-xfstests -c <config> ...) but not for ltm commands (gce-xfstests ltm -c <config> ...).  If you attempt to use --no-email for an ltm command, the tests will run but sharder.emailReport() will panic due to no email address causing the results not to get packed and uploaded to gce.

sharder.go:

    func (sharder *ShardScheduler) finish()  {
        sharder.log.Debug("Finishing sharder")

        sharder.aggResults()
        sharder.createInfo()
        sharder.createRunStats()
        sharder.genResultsSummary()

        if !sharder.reportKCS {
            sharder.emailReport() -> panic'ing because no where to send email
        }

        sharder.packResults()
    }

**Comment by tytso** [comment]
I've also fixed up the appliance and ltm-kcs selftests to no longer send-emails, and ltm-kcs now vaidates the test results files (as opposed to relying on the human to verify the e-mail'ed reports).
