### ISSUE TITLE
Build failed (fsverity-utils.git has gone)

### ISSUE THREAD

**Issue by Cypresslin** [tytso/xfstests-bld#47]
When trying to build xfstest-bld, `get-all` will fail with:

    Running './get-all'
    
    Cloning into 'fio'...
    warning: redirecting to https://git.kernel.dk/fio.git/
    Checking out fio fio-3.15 (previously was fio-3.33-96-gded6cce8)
    
    Cloning into 'quota'...
    Checking out quota 6e631074330a (previously was v4.05-53-gd90b7d5)
    
    Cloning into 'xfsprogs-dev'...
    Checking out xfsprogs-dev v5.2.0 (previously was v6.1.1)
    
    Cloning into 'xfstests-dev'...
    
    Cloning into 'fsverity'...
    fatal: repository 'https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git/' not found
    Failed to clone fsverity from https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git/

It looks like https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git/ does not exist anymore.

**Comment by ebiggers** [comment]
The fsverity-utils repo has moved, see pull request https://github.com/tytso/xfstests-bld/pull/38 from last month.

**Comment by Cypresslin** [comment]
PR #38 merged, closing this issue.
Thanks!
